use_frameworks!

platform :ios, '10.0'

target 'PioerDebugService_Example' do
  pod 'PioerDebugService', :path => '../'

  target 'PioerDebugService_Tests' do
    inherit! :search_paths

    
  end
end
